# Generated by Django 5.1.2 on 2024-10-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_car_caritem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CarItem',
            new_name='CartItem',
        ),
    ]
